<script type="text/javascript" src="<?php echo Mage::helper('inpostparcels/data')->getGeowidgetUrl(); ?>"></script>
<script type="text/javascript">
    function user_function(value) {
        var address = value.split(';');
        //document.getElementById('town').value=address[1];
        //document.getElementById('street').value=address[2]+address[3];
        var box_machine_name = document.getElementById('name').value;
        var box_machine_town = document.value=address[1];
        var box_machine_street = document.value=address[2];


        var is_value = 0;
        document.getElementById('shipping_inpostparcels').value = box_machine_name;
        var shipping_inpostparcels = document.getElementById('shipping_inpostparcels');

        for(i=0;i<shipping_inpostparcels.length;i++){
            if(shipping_inpostparcels.options[i].value == document.getElementById('name').value){
                shipping_inpostparcels.selectedIndex = i;
                is_value = 1;
            }
        }

        if (is_value == 0){
            shipping_inpostparcels.options[shipping_inpostparcels.options.length] = new Option(box_machine_name+','+box_machine_town+','+box_machine_street, box_machine_name);
            shipping_inpostparcels.selectedIndex = shipping_inpostparcels.length-1;
        }
    }
</script>

<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
    <?php $shippingCodePrice = array(); ?>
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <?php if($this->getCarrierName($code) != 'Inpostparcels'): ?>
            <dt><?php echo $this->getCarrierName($code) ?></dt>
        <?php else: ?>
            <dt><?php echo Mage::getStoreConfig('carriers/inpostparcels/name'); ?></dt>
        <?php endif; ?>
        <dd>
            <ul>
            <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                    <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                   <?php else: ?>
                        <?php if ($_sole) : ?>
                        <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                        <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                        <script type="text/javascript">
                            //<![CDATA[
                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                            //]]>
                        </script>
                        <?php endif; ?>

                        <?php endif; ?>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                        </label>
                        <?php
                        	$carrier = Mage::getModel('shipping/config')->getCarrierInstance($code);
                            if($carrier->getFormBlock()){
                        		$block = $this->getLayout()->createBlock($carrier->getFormBlock());
                        		$block->setMethodCode($code);
                        		$block->setRate($_rate);
                        		$block->setMethodInstance($carrier);
                        		echo $block->_toHtml();
                        	}
                        ?>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
    <?php endforeach; ?>
    </dl>
<script type="text/javascript">
//<![CDATA[
    <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
    <?php endif; ?>

    $$('input[type="radio"][name="shipping_method"]').each(function(el){
        Event.observe(el, 'click', function(){
            if (el.checked == true) {
                var getShippingCode = el.getValue();
                <?php if (!empty($shippingCodePrice)): ?>
                    var newPrice = shippingCodePrice[getShippingCode];
                    if (!lastPrice) {
                        lastPrice = newPrice;
                        quoteBaseGrandTotal += newPrice;
                    }
                    if (newPrice != lastPrice) {
                        quoteBaseGrandTotal += (newPrice-lastPrice);
                        lastPrice = newPrice;
                    }
                <?php endif; ?>
                checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                return false;
            }
       });
    });
//]]>
jQuery(document).ready(function(){
	hideShippingAll();
	jQuery('input[type="radio"][name="shipping_method"]').click(function(){
			hideShippingAll();
			var code = jQuery(this).val();
			if(jQuery(this).is(':checked')){
				showShipping(code);
			}
	});
	jQuery('input[type="radio"][name="shipping_method"]').each(function(){
		var code = jQuery(this).val();
		if(jQuery(this).is(":checked")){
			showShipping(code);
		}
	});
});
function showShipping(code){
	if(jQuery('#'+'shipping_form_'+code).length != 0){
		jQuery('#'+'shipping_form_'+code).show();
		jQuery(this).find('.required-entry').attr('disabled','false');
	}
}
function hideShippingAll(){
	jQuery('input[type="radio"][name="shipping_method"]').each(function(){
		var code = jQuery(this).val();
		jQuery('#'+'shipping_form_'+code).hide();
		jQuery(this).find('.required-entry').attr('disabled','true');
	});
}

Validation.add('inpostparcels_phone', '<?php echo $this->__('Phone validation error')?>', {
    pattern : /^[1-9]{1}\d{8}$/
});

</script>
<?php endif; ?>